version: '3.3'
services:
    users_backend:
      build: .
      ports:
        - "8001:8000"
      volumes:
        - .:/app
      depends_on:
        - users_db

    users_db:
      image: mysql:5.7.22
      restart: always
      environment:
        MYSQL_DATABASE: users
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - .dbdata:/var/lib/mysql