version: '3'
services:
  users_backend:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: users:0.0.2
    ports:
      - "8001:8000"
    environment:
      DB_HOST: 34.159.37.86
      DB_PORT: 3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root